// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   throw UnsupportedError(
    //     'DefaultFirebaseOptions have not been configured for web - '
    //     'you can reconfigure this by running the FlutterFire CLI again.',
    //   );
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xSXM3WMc8a11u1Dp4Dco8XJjpbawUnw',
    appId: '1:117938042068:android:2c128039076c3084f9b741',
    messagingSenderId: '117938042068',
    projectId: 'tiktok-clone-4fde1',
    storageBucket: 'tiktok-clone-4fde1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbFoKn1I6d0jyzURdTH9yDzZ_zSNYNb_Q',
    appId: '1:117938042068:ios:ac5a53e5acf3290af9b741',
    messagingSenderId: '117938042068',
    projectId: 'tiktok-clone-4fde1',
    storageBucket: 'tiktok-clone-4fde1.appspot.com',
    iosBundleId: 'com.example.tiktokClone2',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8xSXM3WMc8a11u1Dp4Dco8XJjpbawUnw',
    appId: '1:117938042068:android:2c128039076c3084f9b741',
    messagingSenderId: '117938042068',
    projectId: 'tiktok-clone-4fde1',
    storageBucket: 'tiktok-clone-4fde1.appspot.com',
  );
}
